### ISSUE TITLE
Problem with the genatklayer command

### ISSUE THREAD

**Issue by davidjwaugh** [daveherrald/SA-attck_nav#11]
Hello
We are using the App in Splunk and am having issues with the genatklayer command.

It works for the master_layer , but we don't seem to be able to generate new  layers that are stored in the Splunk KVstore.

For example running the results

`| makeresults 1 | eval technique="T1089" | eval detected=1 | genatklayer  name="test"`

Produced the result "Unrecognized option: name=test"
![Capture](https://user-images.githubusercontent.com/15192521/68395524-c36a3c00-0167-11ea-88f5-32490a1700b6.PNG)

Is it possible to have another layer in the application that is stored in the KVStore?

**Comment by splunkchamp** [comment]
Hey @davidjwaugh ! That hasn't actually been implemented yet. I think I left some stub methods in the search command, but I'll likely add that functionality in the next month or so.

**Comment by davidjwaugh** [comment]
Thanks very much. Do you think this will ever make it to be an official
Splunk App?

**Comment by splunkchamp** [comment]
@davidjwaugh I just added support for this in the custom search command. Check the conf2019 branch for this new code and provide feedback!
